"""empty message

Revision ID: 8b8ff3e78fba
Revises: 147c08d69b76
Create Date: 2026-07-20 18:20:31.929095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b8ff3e78fba'
down_revision: Union[str, Sequence[str], None] = '147c08d69b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultations_department'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_patient'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_patients_name'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('drug_details')
    op.drop_table('departments')
    op.drop_index(op.f('ix_diseases_name'), table_name='diseases')
    op.drop_table('diseases')
    op.drop_index(op.f('ix_disease_drugs_disease'), table_name='disease_drugs')
    op.drop_index(op.f('ix_disease_drugs_drug'), table_name='disease_drugs')
    op.drop_table('disease_drugs')
    op.drop_index(op.f('ix_drugs_category'), table_name='drugs')
    op.drop_index(op.f('ix_drugs_name'), table_name='drugs')
    op.drop_table('drugs')
    op.drop_index(op.f('ix_symptoms_name'), table_name='symptoms')
    op.drop_table('symptoms')
    op.drop_index(op.f('ix_disease_symptoms_disease'), table_name='disease_symptoms')
    op.drop_index(op.f('ix_disease_symptoms_symptom'), table_name='disease_symptoms')
    op.drop_table('disease_symptoms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease_symptoms',
    sa.Column('disease_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='疾病 ID'),
    sa.Column('symptom_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='症状 ID'),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], name=op.f('disease_symptoms_disease_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], name=op.f('disease_symptoms_symptom_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('disease_symptoms_pkey'))
    )
    op.create_index(op.f('ix_disease_symptoms_symptom'), 'disease_symptoms', ['symptom_id'], unique=False)
    op.create_index(op.f('ix_disease_symptoms_disease'), 'disease_symptoms', ['disease_id'], unique=False)
    op.create_table('symptoms',
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='症状名称，如：发热、头痛'),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('symptoms_pkey')),
    sa.UniqueConstraint('name', name=op.f('symptoms_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_symptoms_name'), 'symptoms', ['name'], unique=False)
    op.create_table('drugs',
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='药品通用名'),
    sa.Column('alias', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='别名/商品名，多个用逗号分隔'),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='药品分类，如：抗生素、解热镇痛'),
    sa.Column('manufacturer', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='生产厂家'),
    sa.Column('approval_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='国药准字批准文号'),
    sa.Column('is_otc', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否为非处方药（OTC）'),
    sa.Column('stock_quantity', sa.INTEGER(), autoincrement=False, nullable=True, comment='库存数量（运营统计用）'),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='参考零售价（元）'),
    sa.Column('expire_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='有效期至，格式：YYYY-MM-DD'),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('drugs_pkey'))
    )
    op.create_index(op.f('ix_drugs_name'), 'drugs', ['name'], unique=False)
    op.create_index(op.f('ix_drugs_category'), 'drugs', ['category'], unique=False)
    op.create_table('disease_drugs',
    sa.Column('disease_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='疾病 ID'),
    sa.Column('drug_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='药品 ID'),
    sa.Column('relation_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='关系类型：common=常用药 / recommend=推荐药'),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], name=op.f('disease_drugs_disease_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], name=op.f('disease_drugs_drug_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('disease_drugs_pkey'))
    )
    op.create_index(op.f('ix_disease_drugs_drug'), 'disease_drugs', ['drug_id'], unique=False)
    op.create_index(op.f('ix_disease_drugs_disease'), 'disease_drugs', ['disease_id'], unique=False)
    op.create_table('diseases',
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='疾病名称'),
    sa.Column('department_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='所属科室 ID'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='疾病描述/定义'),
    sa.Column('cause', sa.TEXT(), autoincrement=False, nullable=True, comment='病因'),
    sa.Column('prevent', sa.TEXT(), autoincrement=False, nullable=True, comment='预防措施'),
    sa.Column('cure_way', sa.TEXT(), autoincrement=False, nullable=True, comment='治疗方式，多种方式用逗号分隔'),
    sa.Column('cure_lasttime', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='治疗周期，如：1-2个月'),
    sa.Column('cured_prob', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='治愈概率，如：95%'),
    sa.Column('easy_get', sa.TEXT(), autoincrement=False, nullable=True, comment='易感人群描述'),
    sa.Column('cost_money', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='参考费用区间'),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('diseases_department_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('diseases_pkey')),
    sa.UniqueConstraint('name', name=op.f('diseases_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_diseases_name'), 'diseases', ['name'], unique=False)
    op.create_table('departments',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='科室名称，如：内科、外科'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='科室简介'),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('departments_pkey')),
    sa.UniqueConstraint('name', name=op.f('departments_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('drug_details',
    sa.Column('drug_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='关联药品 ID'),
    sa.Column('indication', sa.TEXT(), autoincrement=False, nullable=True, comment='适应症/功能主治'),
    sa.Column('usage_dosage', sa.TEXT(), autoincrement=False, nullable=True, comment='用法用量'),
    sa.Column('adverse_reaction', sa.TEXT(), autoincrement=False, nullable=True, comment='不良反应'),
    sa.Column('contraindication', sa.TEXT(), autoincrement=False, nullable=True, comment='禁忌症'),
    sa.Column('precaution', sa.TEXT(), autoincrement=False, nullable=True, comment='注意事项'),
    sa.Column('interaction', sa.TEXT(), autoincrement=False, nullable=True, comment='药物相互作用（文本描述，结构化关系在 Neo4j）'),
    sa.Column('storage', sa.TEXT(), autoincrement=False, nullable=True, comment='储存条件'),
    sa.Column('full_instruction', sa.TEXT(), autoincrement=False, nullable=True, comment='完整说明书原文（RAG 切片用）'),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], name=op.f('drug_details_drug_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('drug_details_pkey')),
    sa.UniqueConstraint('drug_id', name=op.f('drug_details_drug_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('patients',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='患者姓名'),
    sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='性别：男/女'),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True, comment='年龄'),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='联系电话'),
    sa.Column('id_card', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='身份证号（脱敏存储）'),
    sa.Column('allergy_history', sa.TEXT(), autoincrement=False, nullable=True, comment='过敏史，多种用逗号分隔'),
    sa.Column('medical_history', sa.TEXT(), autoincrement=False, nullable=True, comment='既往病史'),
    sa.Column('blood_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='血型，如：A/B/O/AB'),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('patients_pkey'))
    )
    op.create_index(op.f('ix_patients_name'), 'patients', ['name'], unique=False)
    op.create_table('consultations',
    sa.Column('patient_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='患者 ID'),
    sa.Column('department_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='就诊科室 ID'),
    sa.Column('chief_complaint', sa.TEXT(), autoincrement=False, nullable=True, comment='主诉（患者自述症状）'),
    sa.Column('diagnosis', sa.TEXT(), autoincrement=False, nullable=True, comment='诊断结论'),
    sa.Column('prescription', sa.TEXT(), autoincrement=False, nullable=True, comment='处方内容（JSON 字符串）'),
    sa.Column('urgency_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='紧急程度：normal=普通 / urgent=较急 / emergency=紧急'),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='关联的 Redis 会话 ID'),
    sa.Column('milvus_doc_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='向量化后在 Milvus 中的文档 ID'),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('consultations_department_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('consultations_patient_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('consultations_pkey'))
    )
    op.create_index(op.f('ix_consultations_patient'), 'consultations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_consultations_department'), 'consultations', ['department_id'], unique=False)
    # ### end Alembic commands ###
