"""make consultation patient_id nullable

Revision ID: aeb9b520f7f5
Revises: 56b80cf07752
Create Date: 2026-07-22 14:29:34.758559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeb9b520f7f5'
down_revision: Union[str, Sequence[str], None] = '56b80cf07752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consultations', 'patient_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               comment='患者 ID（非登录用户可为空）',
               existing_comment='患者 ID')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consultations', 'patient_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               comment='患者 ID',
               existing_comment='患者 ID（非登录用户可为空）')
    # ### end Alembic commands ###
